package it.chalmers.tendu.event;

/** Constants for Eventmessage use */ 
public class C {

	public enum Tag {
		TEST, DEFAULT, 
		
		// *** Network ***
		COMMAND_AS_HOST, 
		HOST_COMMANDED, 
		REQUEST_AS_CLIENT, 
		CLIENT_REQUESTED, 
		NETWORK_NOTIFICATION,
		
		TO_SELF;
	}

	public enum Msg {
		TEST, 
		
		// *** Network ***
		ALL_PLAYERS_CONNECTED,
		PLAYER_CONNECTED,
		CONNECTION_LOST,
		PLAYER_DISCONNECTED, 
		STOP_ACCEPTING_CONNECTIONS,
		
		LOBBY_READY, 
		LOAD_GAME, 
		NUMBER_GUESS, 
		UPDATE_MODEL, 
		REMOVE_TIME, 
		PLAYER_READY, 
		UPDATE_LOBBY_MODEL, 
		START_MINI_GAME, 
		GAME_SESSION_MODEL, 
		SHAPE_SENT, 
		LOCK_ATTEMPT, 
		LOCK_FINISHED, 
		CREATE_SCREEN, 
		WAITING_TO_START_GAME, 
		
		// *** Sound ***
		SOUND_WIN, SOUND_LOST, SOUND_SUCCEED, SOUND_FAIL, 
		
		INTERIM_FINISHED, 
		GAME_RESULT, 
		SHOW_INTERIM_SCREEN, 
		SHOW_GAME_OVER_SCREEN, 
		PLAYER_REPLAY_READY, 
		RETURN_MAIN_MENU, 
		RESTART;
	}
}
