package it.chalmers.tendu.tbd;

public class C {

	public enum Tag {
		TEST, COMMAND_AS_HOST, HOST_COMMANDED, REQUEST_AS_CLIENT, CLIENT_REQUESTED, DEFAULT, TO_SELF, NETWORK_NOTIFICATION;
	}

	public enum Msg {
		TEST, ALL_PLAYERS_CONNECTED, LOBBY_READY, LOAD_THIS_GAME, NUMBER_GUESS, UPDATE_MODEL, PLAYER_CONNECTED, CONNECTION_LOST, REMOVE_TIME, PLAYER_READY, UPDATE_LOBBY_MODEL, START_MINI_GAME, GAME_SESSION_MODEL, SHAPE_SENT, LOCK_ATTEMPT, LOCK_FINISHED, CREATE_SCREEN, WAITING_TO_START_GAME;
	}
}
