package it.chalmers.tendu.tbd;

public class C {

	public enum Tag  {
		COMMAND_AS_HOST, HOST_COMMANDED, REQUEST_AS_CLIENT, CLIENT_REQUESTED, DEFAULT, ACCESS_MODEL, NETWORK_NOTIFICATION;
	}
	
	public enum Msg  {
		ALL_PLAYERS_CONNECTED, LOBBY_READY, LOAD_THIS_GAME, NUMBER_GUESS, UPDATE_MODEL, PLAYER_CONNECTED, CONNECTION_LOST;
	}
}

